### PR TITLE
node: add full node p2p stream test

### PR DESCRIPTION
**Pull request by renaynay**
This PR adds the following test to #57 : `TestFull_P2P_Streams` - to test `Full` nodes' ability to communicate via libp2p streams. This tests that `Host`s are properly started on the node and are able to connect to other nodes directly.

### CODE REVIEW

**Review by Wondertan — APPROVED** [review]
I am totally ok to merge this, as it does not hurt and gave you some experience with libp2p. 

However, I will repeat myself again that the test here does not test any of our functionality, but tests the dependency. You may argue that the test is needed to verify that ___our___ Nodes can connect to each other, but if we trust our dependency who handles connections and stuff, we don't need to verify that.

Note that the tests like this are also a known source of flakiness and increase test run time on CI substantially.

**Comment by renaynay** [comment]
> I am totally ok to merge this, as it does not hurt and gave you some experience with libp2p.
> 
> However, I will repeat myself again that the test here does not test any of our functionality, but tests the dependency. You may argue that the test is needed to verify that _**our**_ Nodes can connect to each other, but if we trust our dependency who handles connections and stuff, we don't need to verify that.
> 
> Note that the tests like this are also a known source of flakiness and increase test run time on CI substantially.

I'm okay with scrapping these tests once we have a CI pipeline that regularly runs full integration tests.

**Comment by liamsi** [comment]
Can this be rebased on the branch? Or maybe #57 can actually be merged independently and this can then target master instead?

**Comment by liamsi** [comment]
BTW IMO these tests are useful in the sense that they document that we are marching into the right direction.

**Comment by renaynay** [comment]
@liamsi yeah let's merge this on master after we've merged #57  -- I'll rebase it now and then change target once #57 is merged.

**Pull request closed without merging**
