### PR TITLE
header/store: use an atomic.Pointer instead of Lock

### LINKED ISSUE #864: header/store: Use `RLock` instead of `Lock` inside `Append` during adjacency verification
Ref https://github.com/celestiaorg/celestia-node/issues/861#issuecomment-1167378119

### PR DESCRIPTION
**Pull request by Martichou**
The verification of the headers can be done with only a RLock. By doing so, we provide a "very minor optimization" that can avoid the Lock to wait for processIncoming to finish (as he can take the lock).

Moving the verification to a separate function so that the deref for the RLock is scoped only to the needed part.
An alternative to this would be to get rid of the `defer s.writeLk.RUnlock()` and add a `s.writeLk.RUnlock()` at each return/exit of the function manually (but this wouldn't handle panic!() cases), so might be a no-go.

Close #864

### CODE REVIEW

**Review by Wondertan — CHANGES_REQUESTED** [review]
Thanks for the contribution. 

The code LGTM, but it _really_ does not give us anything in the way it is used currently by Syncer. The (negligible, if existing) contention between reads and writes is still there even with RWMutex. The change would give us something if there were multiple processIncoming routines trying to Append.

We still can proceed with this though by keeping the Header atomically instead of locking it with new [atomic.Pointer](https://pkg.go.dev/sync/atomic#Pointer.Swap) in go1.19.

Let's do this after our update in #1067

**Comment by Martichou** [comment]
Hi, thanks for the feedback ! 

I know it's not a "very important" nor really useful change, it was mainly for me to take my hands on the project's code :).
I'll keep an eyes on #1067 and update this PR accordingly.

**Comment by Wondertan** [comment]
Pls rebase on main, rather than merge main in

**Comment by Martichou** [comment]
@Wondertan oups, my bad ! (done)

**Comment by Wondertan** [comment]
@Martichou, so the #1067 was finally merged, so we can rebase this one and merge it as well 🎉

**Comment by Martichou** [comment]
@Wondertan done ! :tada:

**Comment by Martichou** [comment]
@Wondertan from the CI trace it seems like `TestFullReconstructFromLights` failed with:
```
2022-09-21T15:17:00.2118990Z     reconstruct_test.go:180: 
2022-09-21T15:17:00.2119894Z         	Error Trace:	/home/runner/work/celestia-node/celestia-node/node/tests/reconstruct_test.go:180
2022-09-21T15:17:00.2120464Z         	Error:      	Received unexpected error:
2022-09-21T15:17:00.2121307Z         	            	da: data not available
2022-09-21T15:17:00.2121804Z         	Test:       	TestFullReconstructFromLights
```

I've ran the tests locally (with and without race detection) and they passed everytimes. Do you have any idea on what can cause such issue on the CI ?

**Review by renaynay — APPROVED** [review]
Ran this against arabica, looks good to me.

**Comment by renaynay** [comment]
@Martichou likely flakiness in our tests - your code doesn't impact this.

**Review by Wondertan — APPROVED** [review]

**Pull request merged**
