### PR TITLE
Revert "Merge pull request #297 from celestiaorg/hlib/deps-update"

### PR DESCRIPTION
**Pull request by Bidon15**
This reverts commit 078cc6a56402490891947a44f04ca9efda972c10, reversing
changes made to afc153d5d8c7c07f835461cedc5c7b04e57a8034.

### CODE REVIEW

**Comment by adlerjohn** [comment]
What's the need for this, if any?

**Comment by Bidon15** [comment]
> What's the need for this, if any?

It was needed to answer the Q why we suddenly observe staticcheck errors 

I'll close this PR as we merge the updated version of golangci-lint

**Comment by adlerjohn** [comment]
Ref: #308

**Comment by Wondertan** [comment]
Closing as #308 is merged now

**Pull request closed without merging**
