### PR TITLE
recompute hash

### PR DESCRIPTION
**Pull request by expertdicer**
Closes: #2959 
Recompute hash for the ExtendedHeader

### CODE REVIEW

**Comment by Wondertan** [comment]
@expertdicer, let's add caching for this cache, so we compute it only on the first Hash call

**Comment by Wondertan** [comment]
Hey @expertdicer, do you want to finish this PR, or should we take over?

**Comment by renaynay** [comment]
Hey @expertdicer we're gonna take this one over, thanks

**Comment by cristaloleg** [comment]
Done in #3975 closing.

**Pull request closed without merging**
