### PR TITLE
deps!: bump nmt, breaking JSON RPC return types including nmt Proofs

### PR DESCRIPTION
**Pull request by distractedm1nd**
Related: https://github.com/celestiaorg/nmt/pull/233

### CODE REVIEW

**Comment by Wondertan** [comment]
Why is it breaking again?

**Comment by distractedm1nd** [comment]
@Wondertan https://github.com/celestiaorg/celestia-node/issues/2631

**Review by ramin — COMMENTED** [review]
Do we have to do follow on work to fix rpc after this?

**Comment by distractedm1nd** [comment]
@ramin Yes! We need to update the openrpc json after this, but its not in main yet

**Review by ramin — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Pull request merged**
