### PR TITLE
feat!: Move Dockerfile to the root of the project

### PR DESCRIPTION
**Pull request by jrmanes**
## Overview

Hello team,

This is an small change.

In order to standardize the repositories, I've moved the `Dockerfile` from the `docker` folder to the root of the project as `celestia-app` is, keeping the `docker` folder for possible uses like, creating other `Dockerfiles`, scripts, etc...
Next step will be to use a common CI from the `.github` repository.

## Checklist

- [x] Required CI checks are passing
- [x] Linked issues closed with keywords

--- 
Closes Issue: [38](https://github.com/celestiaorg/devops/issues/38)

### CODE REVIEW

**Review by renaynay — APPROVED** [review]
fine with me

**Review by sysrex — CHANGES_REQUESTED** [review]
LGTM

**Review by sysrex — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]
lgtm

**Review by renaynay — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Review by Bidon15 — APPROVED** [review]
:shipit:

**Comment by jrmanes** [comment]
hey team!
thank you all for the review! 😊 

I'll need a volunteer to click on merge when you can 😇

thanks in advance!

**Pull request merged**
