### PR TITLE
refactor(availability): use functional options pattern to configure availability implementations

### PR DESCRIPTION
**Pull request by derrandz**
# Overview

The codebase is currently littered with default constant global variables acting as configuration variables.
This makes changing configuration values for the Celestia node non-trivial, as it requires code changes and binary re-building.

In this PR, we refactor the global configuration variables logic to use the functional options pattern, which will trivialize the process of configuring a Celestia node.

# Reference Issue(s)
#709 
#1063  

# Impact

Notable changes:

- Changes made to the `Availability` interface
- Factorized Options for all `Availability` implementations in one place
   - Included `Discovery` in the equation by defining the `Discoverable` interface and defining default parameters and providing functional options to the `Discovery` implementation
- Adding functional options to constructors changed the `Availability` implementations' constructors to return both the created instance and an error if params are invalid.

*This means for the reviewer that*:

- You can start by reviewing:

   1. `share/availability.go`
   2. `share/availability/options.go`
   3. `share/availability/light/availability.go`
   4. `share/availability/full/availability.go`
   5. `share/availability/cache/availability.go`
   6. `share/availability/discovery/discovery.go`
   7. `nodebuilder/share/*.go`

The rest of the changes are just side-effects composing mainly of changes to tests because of constructor signature changes (_now returning errors as well_).

# Dependencies

Blocked by #1177

### CODE REVIEW

**Comment by derrandz** [comment]
@renaynay yes

**Comment by renaynay** [comment]
Closing in favour of #1225

**Review by derrandz — COMMENTED** [review]
While iterating on this PR, I've ran into the following issue https://github.com/celestiaorg/celestia-node/issues/1306

I've traced it to the following lines:

- [rpc_test](https://github.com/celestiaorg/celestia-node/pull/1224/files#diff-ce39e7cc74ab9bdfcedaa92ae1d24bdad712398bc0315dfe59439bb15f4a7eceR42-R43)
- [client_test](https://github.com/celestiaorg/celestia-node/pull/1224/files#diff-b1a26e7880f62357e4b2e511c9d3eb41ac373db5f37b6a0d1cbc427053fd6847R23)
- [fetcher_test](https://github.com/celestiaorg/celestia-node/pull/1224/files#diff-5873676f9af35df5d59344ebe68ab23dc1dd794f9df73a7974809cc6162b047aR44)
- [reconstruction_test (1)](https://github.com/celestiaorg/celestia-node/pull/1224/files#diff-8bb7d47b91a14ab1822f5b5b5f3dd30ba46e63b12e3463493012cffcbf3b7a0eR226-R228)
- [reconstruction_test (2)](https://github.com/celestiaorg/celestia-node/pull/1224/files#diff-8bb7d47b91a14ab1822f5b5b5f3dd30ba46e63b12e3463493012cffcbf3b7a0eR239-R240)

**Comment by Wondertan** [comment]
@derrandz, needs rebase

**Comment by derrandz** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-node/pull/1798

**Pull request closed without merging**
