### PR TITLE
feat: local docker telemetry infra

### PR DESCRIPTION
**Pull request by distractedm1nd**
Supersedes #1990

Adds local telemetry infra to the Makefile. This includes pyroscope, grafana, jaeger, an otel-collector, prometheus, and loki.

### CODE REVIEW

**Review by renaynay — APPROVED** [review]
I'm fine with this just yamllint

**Comment by Wondertan** [comment]
@musalbas

**Review by derrandz — APPROVED** [review]
glad to see this finally coming useful

**Review by renaynay — APPROVED** [review]
Lets go

**Review by vgonkivs — APPROVED** [review]

**Pull request merged**
