### PR TITLE
feat(header): Check app version in eh validation and return err on mismatch

### PR DESCRIPTION
**Pull request by renaynay**
As recommended by @cmwaters, we should ensure (as a rudimentary check) that the headers being passed to us from core match in app versions as upgraded app versions can indicate breaking changes. 

We should error out if the app version does not match.

This PR is still draft until celestia-app has a version out where they export the AppVersion as a const that we can depend on. 

Eventually we should support several versions via #2137 but for now, this is a good enough check.

TODO: 
- [x] depend on const from app
- [x] test

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
Yeah this works for now

**Review by Wondertan — DISMISSED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Comment by renaynay** [comment]
Wait a sec

```
--- FAIL: TestBlobService_Get (0.01s)
    service_test.go:222:
        	Error Trace:	/Users/rene/go/src/github.com/renaynay/celestia-node/blob/service_test.go:222
        	            				/Users/rene/go/src/github.com/renaynay/celestia-node/blob/service_test.go:295
        	Error:      	Received unexpected error:
        	            	share data must be 512 bytes, got 0
        	Test:       	TestBlobService_Get
    --- FAIL: TestBlobService_Get/not_included (0.00s)
        testing.go:1471: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
```

**Comment by renaynay** [comment]
```
--- FAIL: TestListenerWithNonEmptyBlocks (60.02s)
    listener_test.go:105:
        	Error Trace:	/Users/rene/go/src/github.com/renaynay/celestia-node/core/listener_test.go:105
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestListenerWithNonEmptyBlocks
    listener_test.go:181:
        	Error Trace:	/Users/rene/go/src/github.com/renaynay/celestia-node/core/listener_test.go:181
        	            				/opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:1150
        	            				/opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:1328
        	            				/opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:1570
        	            				/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:522
        	            				/opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:980
        	            				/Users/rene/go/src/github.com/renaynay/celestia-node/core/listener_test.go:105
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestListenerWithNonEmptyBlocks
FAIL

```

will investigate

**Comment by renaynay** [comment]
waiting on @cmwaters to update testnode in core to set app version

**Review by distractedm1nd — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]

**Pull request merged**
