### PR TITLE
chore: bump libp2p

### PR DESCRIPTION
**Pull request by Wondertan**
Bumps version to [v0.29](https://github.com/libp2p/go-libp2p/releases/tag/v0.29.0). The main gist from the release is behind [figures](https://github.com/libp2p/go-libp2p/issues/2326#issuecomment-1644332863) showing the efficiency of the new dialing strategy. 

Also updates other steps, including quic which is now more optimized since minor versions we missed.

### CODE REVIEW

**Comment by walldiss** [comment]
Lets update deprecated "github.com/libp2p/go-libp2p/p2p/host/resource-manager/obs"

**Comment by Wondertan** [comment]
We can remove that line altogether as its now done automatically

**Review by walldiss — APPROVED** [review]

**Review by renaynay — COMMENTED** [review]
rcmgr/obs is still in nodebuilder/p2p/resources file

**Comment by Wondertan** [comment]
image

**Review by renaynay — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Pull request merged**
