### PR TITLE
Add cel-key utility to Docker images

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Closes https://github.com/celestiaorg/celestia-node/issues/1621 and makes https://github.com/celestiaorg/docs/issues/402 possible

## Checklist

- [x] New and updated code has appropriate documentation https://github.com/celestiaorg/docs/pull/453
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords https://github.com/celestiaorg/celestia-node/issues/1621

### CODE REVIEW

**Review by distractedm1nd — APPROVED** [review]

**Comment by jcstein** [comment]
Tested out with @Bidon15 and it works as expected!

**Comment by Bidon15** [comment]
Ser @jcstein , could you please rebase and fix some linter warnings? 👐

**Comment by jcstein** [comment]
Yes I just saw this, will ping you tomorrow if I run into an issue. Hoping to get this merged soon

**Comment by jcstein** [comment]
rebased ✅ 

however for `hadolint` i only see a Warning and not an error? https://github.com/celestiaorg/celestia-node/actions/runs/4110144252/jobs/7092683736#step:4:12

**Comment by Bidon15** [comment]
> rebased ✅

ser, you are 🅱️ 

> however for `hadolint` i only see a workflow-related Warning and not an Error, @Bidon15? https://github.com/celestiaorg/celestia-node/actions/runs/4110144252/jobs/7092683736#step:4:12

Try running the linter locally against your dockerimage changes in this PR
https://hub.docker.com/r/hadolint/hadolint

I guess the workflow is not displaying the actual linter error 😓 
lemme know if smt goes sideways 🙏

**Comment by jcstein** [comment]
yea i'm used to `set-output` errors involving someone pushing to a directory where they don't have permissions to run the workflow because they don't have write perms for the repo

okay. thanks, checking now

**Comment by jcstein** [comment]
yea i'm used to set-output errors involving someone pushing to a directory where they don't have permissions to run the workflow

okay. thanks, this is what I get:
```bash
docker/Dockerfile:11 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
```

Combined the lines for: `RUN make build && make cel-key`

it's probably best if someone who is more familiar with this all reviews this, too. it looks like Dockerfile is now in root on main

**Comment by jcstein** [comment]
Tested out the container with changes in https://github.com/celestiaorg/celestia-node/pull/1672/commits/2343763f13840f839a1383a9c0355c98514d5a38:

```bash
jcs @ ~/DEV/celestia-node % docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS                                NAMES
07dd77e0b442   celestia-node   "/entrypoint.sh cele…"   11 seconds ago   Up 10 seconds   2121/tcp, 0.0.0.0:26659->26659/tcp   frosty_mestorf
jcs @ ~/DEV/celestia-node % docker exec -ti celestia-node /bin/bash
Error response from daemon: No such container: celestia-node
jcs @ ~/DEV/celestia-node % docker exec -ti 07dd77e0b442 /bin/bash
root@07dd77e0b442:/# ./cel-key list --keyring-backend test --node.type light
using directory:  ~/.celestia-light-mocha/keys
- address: celestia1aruyt2p4g78z0kr2qkxdz0wq2v6k98lzal3z97
  name: my_celes_key
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A/j50Y0cP++akJEBOTD/+TK+k/k8RCk2ABUSRlGgQ0zX"}'
  type: local

root@07dd77e0b442:/# 
```

**Review by Bidon15 — APPROVED** [review]
🚢

**Review by jrmanes — APPROVED** [review]
LGTM 🚀

**Comment by Bidon15** [comment]
> swamp test is not an issue?

nope for this PR. It's a flakey test IIRC

**Review by renaynay — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Pull request merged**
