### PR TITLE
fix(cmd/blob): fix namespace parsing in cli

### LINKED ISSUE #4000: Error: only hex namespace is supported
### Celestia Node version

Commit: 7af07bd08f4eed66fbc9eee47762fd2c3365c89f

### OS

MacOS 

### Install tools

_No response_

### Others

_No response_

### Steps to reproduce it

`celestia blob get 2966903 0f0f0f0f0f0f0f0f0f0f 2efab21bbd40a7d163dee0dd6192245a8bd9d61b0013d7da34a1878e8466e91f --node.store ~/.celestia-light`

### Expected result

output the blob

### Actual result

`Error: only hex namespace is supported`

though the namespace, 0f0f0f0f0f0f0f0f0f0f, is hex.

### Relevant log output

_No response_

### Is the node "stuck"? Has it stopped syncing?

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by vgonkivs**
Closes #4000

### CODE REVIEW

**Review by Wondertan — APPROVED** [review]
Fastest fix on the west

**Comment by vgonkivs** [comment]
🤠

**Comment by Wondertan** [comment]
This solution works, but imo we shoul just have a smart string -> namespace func somewhere in go sqaure

**Review by renaynay — APPROVED** [review]
agree w hlib re go-square comment

**Comment by Wondertan** [comment]
@vgonkivs, care for an issue to go-square?

**Pull request merged**
