### PR TITLE
Remove watchdog since go 1.19 don't need it anymore.

### LINKED ISSUE #1039: Remove go-watchdog once we migrate to 1.19
Watchdog 'solves' the OOM problem when Go aggressively allocates memory on low RAM systems. The quotes are to emphasize that it does not solve the problem completely and is more like a hack when the real problem is in GO's GC. Fortunately, GO 1.19 [solves](https://tip.golang.org/doc/go1.19#runtime) the problem fundamentally by introducing the soft memory limit

### PR DESCRIPTION
**Pull request by HoytRen**
I checked the history that the watchdog is added in Feb. and I don't see many relative. Please review.

Closes #1039

### CODE REVIEW

**Comment by HoytRen** [comment]
Close #1039

**Review by Wondertan — APPROVED** [review]
The integrations tests might fail but this LGTM

**Comment by Wondertan** [comment]
Note that the failures are unrelated to your PR. We can keep this one open for a while until we fix CI and rebase this one on top. Pls also rebase the PR rather than mergin main into

**Comment by HoytRen** [comment]
get it.

**Comment by Wondertan** [comment]
@HoytRen, pls rebase to get the fixed CI, and we can merge it

**Review by vgonkivs — APPROVED** [review]
LGTM

**Comment by Wondertan** [comment]
Thank you @HoytRen

**Pull request merged**
