### PR TITLE
refactor(swamp/tests)skip tests

### PR DESCRIPTION
**Pull request by vgonkivs**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by vgonkivs** [comment]
```
==================
[88](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:89)
WARNING: DATA RACE
[89](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:90)
Write at 0x00c00f2abe40 by goroutine 5541:
[90](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:91)
  sync/atomic.StoreInt64()
[91](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:92)
      /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/race_amd64.s:237 +0xb
[92](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:93)
  sync/atomic.StorePointer()
[93](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:94)
      /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/atomic_pointer.go:82 +0x44
[94](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:95)
  github.com/celestiaorg/celestia-node/share/p2p/peers.(*Manager).newPeer.(*Manager).doneFunc.func1()
[95](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:96)
      /home/runner/work/celestia-node/celestia-node/share/p2p/peers/manager.go:280 +0x32a
[96](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:97)
  github.com/celestiaorg/celestia-node/share/getters.(*ShrexGetter).GetEDS()
[97](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:98)
      /home/runner/work/celestia-node/celestia-node/share/getters/shrex.go:159 +0x9a1
[98](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:99)
  github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS.func1()
[99](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:100)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:61 +0x56
[100](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:101)
  github.com/celestiaorg/celestia-node/share/getters.cascadeGetters[go.shape.*uint8]()
[101](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:102)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:124 +0x7ca
[102](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:103)
  github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS()
[103](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:104)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:64 +0x17b
[104](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:105)
  github.com/celestiaorg/celestia-node/share/availability/full.(*ShareAvailability).SharesAvailable()
[105](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:106)
      /home/runner/work/celestia-node/celestia-node/share/availability/full/availability.go:82 +0x2d2
[106](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:107)
  github.com/celestiaorg/celestia-node/das.(*DASer).sample()
[107](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:108)
      /home/runner/work/celestia-node/celestia-node/das/daser.go:150 +0xd2
[108](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:109)
  github.com/celestiaorg/celestia-node/das.(*DASer).sample-fm()
[109](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:110)
      <autogenerated>:1 +0x55
[110](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:111)
  github.com/celestiaorg/celestia-node/das.(*worker).sample()
[111](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:112)
      /home/runner/work/celestia-node/celestia-node/das/worker.go:114 +0x13e
[112](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:113)
  github.com/celestiaorg/celestia-node/das.(*worker).run()
[113](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:114)
      /home/runner/work/celestia-node/celestia-node/das/worker.go:79 +0x244
[114](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:115)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker.func1()
[115](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:116)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:112 +0x113
[116](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:117)

[117](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:118)
Previous read at 0x00c00f2abe40 by goroutine 5542:
[118](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:119)
  github.com/celestiaorg/celestia-node/share/p2p/peers.(*Manager).Peer()
[119](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:120)
      /home/runner/work/celestia-node/celestia-node/share/p2p/peers/manager.go:226 +0x204
[120](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:121)
  github.com/celestiaorg/celestia-node/share/getters.(*ShrexGetter).GetEDS()
[121](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:122)
      /home/runner/work/celestia-node/celestia-node/share/getters/shrex.go:143 +0x324
[122](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:123)
  github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS.func1()
[123](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:124)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:61 +0x56
[124](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:125)
  github.com/celestiaorg/celestia-node/share/getters.cascadeGetters[go.shape.*uint8]()
[125](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:126)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:124 +0x7ca
[126](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:127)
  github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS()
[127](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:128)
      /home/runner/work/celestia-node/celestia-node/share/getters/cascade.go:64 +0x17b
[128](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:129)
  github.com/celestiaorg/celestia-node/share/availability/full.(*ShareAvailability).SharesAvailable()
[129](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:130)
      /home/runner/work/celestia-node/celestia-node/share/availability/full/availability.go:82 +0x2d2
[130](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:131)
  github.com/celestiaorg/celestia-node/das.(*DASer).sample()
[131](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:132)
      /home/runner/work/celestia-node/celestia-node/das/daser.go:150 +0xd2
[132](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:133)
  github.com/celestiaorg/celestia-node/das.(*DASer).sample-fm()
[133](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:134)
      <autogenerated>:1 +0x55
[134](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:135)
  github.com/celestiaorg/celestia-node/das.(*worker).sample()
[135](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:136)
      /home/runner/work/celestia-node/celestia-node/das/worker.go:114 +0x13e
[136](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:137)
  github.com/celestiaorg/celestia-node/das.(*worker).run()
[137](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:138)
      /home/runner/work/celestia-node/celestia-node/das/worker.go:79 +0x244
[138](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:139)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker.func1()
[139](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:140)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:112 +0x113
[140](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:141)

[141](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:142)
Goroutine 5541 (running) created at:
[142](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:143)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker()
[143](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:144)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:110 +0x484
[144](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:145)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).run()
[145](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:146)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:85 +0x7e7
[146](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:147)
  github.com/celestiaorg/celestia-node/das.(*DASer).Start.func1()
[147](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:148)
      /home/runner/work/celestia-node/celestia-node/das/daser.go:110 +0xb3
[148](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:149)

[149](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:150)
Goroutine 5542 (running) created at:
[150](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:151)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker()
[151](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:152)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:110 +0x484
[152](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:153)
  github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).run()
[153](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:154)
      /home/runner/work/celestia-node/celestia-node/das/coordinator.go:78 +0x8e6
[154](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:155)
  github.com/celestiaorg/celestia-node/das.(*DASer).Start.func1()
[155](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:156)
      /home/runner/work/celestia-node/celestia-node/das/daser.go:110 +0xb3
[156](https://github.com/celestiaorg/celestia-node/actions/runs/6391985820/job/17348326468?pr=2802#step:5:157)
==================
```

**Comment by vgonkivs** [comment]
with `-race` flag
```
--- FAIL: TestSyncAgainstBridge_NonEmptyChain (17.79s)
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:227
    swamp.go:107: 
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:228
        	Error Trace:	/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:107
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:229
        	            				/home/runner/go/pkg/mod/golang.org/x/exp@v0.0.0-20230817173708-d852ddb80c63/maps/maps.go:90
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:230
        	            				/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:106
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:231
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:232
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1347
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:233
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1589
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:234
        	Error:      	Received unexpected error:
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:235
        	            	node: failed to stop within timeout(2m0s): context deadline exceeded
https://github.com/celestiaorg/celestia-node/actions/runs/6393679580/job/17353406273?pr=2802#step:5:236
        	Test:       	TestSyncAgainstBridge_NonEmptyChain
```

**Comment by vgonkivs** [comment]
```
--- FAIL: TestShrexNDFromLights (10.95s)
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:726
    full_node.go:181: tearing down testnode
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:727
    testing.go:1465: race detected during execution of test
```

**Comment by vgonkivs** [comment]
```
--- FAIL: TestSyncLightWithTrustedPeers (25.79s)
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5885)
    swamp.go:107: 
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5886)
        	Error Trace:	/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:107
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5887)
        	            				/home/runner/go/pkg/mod/golang.org/x/exp@v0.0.0-20230817173708-d852ddb80c63/maps/maps.go:90
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5888)
        	            				/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:106
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5889)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5890)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1347
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5891)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1589
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5892)
        	Error:      	Received unexpected error:
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5893
        	            	node: failed to stop within timeout(2m0s): context deadline exceeded
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5894
        	Test:       	TestSyncLightWithTrustedPeers
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5895
    full_node.go:181: tearing down testnode
https://github.com/celestiaorg/celestia-node/actions/runs/6393884735/job/17354064855?pr=2802#step:5:5896
    testing.go:1465: race detected during execution of test
```

**Comment by vgonkivs** [comment]
```
--- FAIL: TestSyncStartStopLightWithBridge (14.26s)
[4762](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4763)
    swamp.go:107: 
[4763](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4764)
        	Error Trace:	/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:107
[4764](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4765)
        	            				/home/runner/go/pkg/mod/golang.org/x/exp@v0.0.0-20230817173708-d852ddb80c63/maps/maps.go:90
[4765](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4766)
        	            				/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:106
[4766](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4767)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169
[4767](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4768)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1347
[4768](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4769)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1589
[4769](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4770)
        	Error:      	Received unexpected error:
[4770](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4771)
        	            	node: failed to stop within timeout(2m0s): context deadline exceeded
[4771](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4772)
        	Test:       	TestSyncStartStopLightWithBridge
[4772](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4773)
    full_node.go:181: tearing down testnode
[4773](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:4774)
    testing.go:1465: race detected during execution of test
```

**Comment by vgonkivs** [comment]
```
--- FAIL: TestSyncLightAgainstFull (16.87s)
[5451](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5452)
    swamp.go:107: 
[5452](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5453)
        	Error Trace:	/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:107
[5453](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5454)
        	            				/home/runner/go/pkg/mod/golang.org/x/exp@v0.0.0-20230817173708-d852ddb80c63/maps/maps.go:90
[5454](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5455)
        	            				/home/runner/work/celestia-node/celestia-node/nodebuilder/tests/swamp/swamp.go:106
[5455](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5456)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169
[5456](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5457)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1347
[5457](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5458)
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1589
[5458](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5459)
        	Error:      	Received unexpected error:
[5459](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5460)
        	            	node: failed to stop within timeout(2m0s): context deadline exceeded
[5460](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5461)
        	Test:       	TestSyncLightAgainstFull
[5461](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5462)
    full_node.go:181: tearing down testnode
[5462](https://github.com/celestiaorg/celestia-node/actions/runs/6394231754/job/17355184018?pr=2802#step:5:5463)
    testing.go:1465: race detected during execution of test
```

**Comment by vgonkivs** [comment]
```
--- FAIL: TestBridgeNodeAsBootstrapper (5.88s)
[1356](https://github.com/celestiaorg/celestia-node/actions/runs/6394494464/job/17356459336#step:5:1357)
    full_node.go:181: tearing down testnode
[1357](https://github.com/celestiaorg/celestia-node/actions/runs/6394494464/job/17356459336#step:5:1358)
    testing.go:1465: race detected during execution of test
```

**Comment by ramin** [comment]
@vgonkivs going to close this one and pick up where you got to in another branch with current set of work on trying to clean up flakiness etc

**Pull request closed without merging**
