### PR TITLE
chore: Add EditorConfig

### PR DESCRIPTION
**Pull request by jrmanes**
## Overview

Hello team!

This is a tiny one, I've added the `.editorconfig` file to the project.

Let me know if you prefer any other config 😄 

Best! 🚀

### CODE REVIEW

**Comment by renaynay** [comment]
What's this for @jrmanes  ?

**Comment by jrmanes** [comment]
> What's this for @jrmanes ?

Hello @renaynay 

This file is used for keeping the same code format in the repository, independently of the IDE/OS that people use.
For example, this fixes the issue that you may have seen in the PRs like:

Screenshot 2023-02-10 at 15 58 14

**Comment by renaynay** [comment]
that's usually caught by lint though @jrmanes

**Comment by jrmanes** [comment]
> that's usually caught by lint though @jrmanes

Ops! okay, we can close this one then 👀

**Pull request closed without merging**
