### PR TITLE
chore: Remove issue templates.

### PR DESCRIPTION
**Pull request by adlerjohn**
Issue templates don't seem to be used by the active contributors, so removing.

### CODE REVIEW

**Review by Wondertan — CHANGES_REQUESTED** [review]
Even if we don't use them, outside contributors use them and have to use them for bug reports, etc.

**Comment by adlerjohn** [comment]
In that case could we instead add an "Other" issue template that's minimal?

**Comment by Wondertan** [comment]
@adlerjohn, what should it look like, wdyt? 

cc @Bidon15

**Comment by adlerjohn** [comment]
It should be set up such that you guys will use it and not have to delete anything from it. Maybe blank if that's what it takes.

**Comment by Bidon15** [comment]
@adlerjohn are you ok with the idea that I can take care of editing existing templates to a better state?

**Comment by adlerjohn** [comment]
> are you ok with the idea that I can take care of editing existing templates to a better state?

Yes

**Comment by adlerjohn** [comment]
Closing in favor of #534

**Pull request closed without merging**
