### PR TITLE
deps!: bumping nmt to v0.19.0, breaking rpc response fields

### PR DESCRIPTION
**Pull request by distractedm1nd**
Related: #2633

### CODE REVIEW

**Comment by Wondertan** [comment]
Changes of the name do not break protos. Changes of the type and fields reorder do.

**Comment by Wondertan** [comment]
> Or does the way it work not care about naming and just uses data types and offsets.

Yes

**Review by renaynay — COMMENTED** [review]
Can we bump when we bump core?

**Comment by distractedm1nd** [comment]
closing in favor of core bump #2646

**Pull request closed without merging**
