### PR TITLE
fraud: fix findings in fraud package

### PR DESCRIPTION
**Pull request by vgonkivs**
Current PR added all non-functional suggestions from #674 .

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Generally seems fine. Nothing inherently stands out.

**Comment by vgonkivs** [comment]
All changes were added to  https://github.com/celestiaorg/celestia-node/pull/820

**Comment by Bidon15** [comment]
Issues for both GoLint and Swamp test in CI should go away with #872

**Review by Wondertan — APPROVED** [review]
Other than error body nits, LGTM

**Review by Bidon15 — APPROVED** [review]

**Review by renaynay — APPROVED** [review]

**Pull request merged**
