### PR TITLE
chore: bump app+core versions

### PR DESCRIPTION
**Pull request by liamsi**
This should fix or at least help a bit with test flakiness

ref: https://github.com/celestiaorg/celestia-node/issues/608#issuecomment-1094761877

### CODE REVIEW

**Comment by liamsi** [comment]
still seeing the same issue in CI btw :-/

**Comment by liamsi** [comment]
Also: `TestSyncLightWithBridge`, `TestSyncFullWithBridge`, `TestSyncLightWithTrustedPeers` fail locally for me as well!

**Comment by adlerjohn** [comment]
Update to https://github.com/celestiaorg/celestia-core/releases/tag/v1.0.1-tm-v0.34.16 to hopefully fix

**Comment by liamsi** [comment]
Looks like even this didn't help either 😢 
```
for sub != nil {
			select {
			case msg := <-sub.Out():
```
`sub.Out()` still causes `nil` pointer exception.

**Comment by adlerjohn** [comment]
wait what haha

**Comment by adlerjohn** [comment]
Superseded by #648

**Pull request closed without merging**
