### PR TITLE
fix(share/eds): print error for stuck register shard

### PR DESCRIPTION
**Pull request by walldiss**
Sometimes register shard can take longer, that provided context timeout. This PR logs errors if register shard is stuck.

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
Is this still the case after all the hangups are removed?

**Comment by walldiss** [comment]
Latest tests shown not hangups. But still, we don't want to lose event of hangup and info all related info of if it happens.

**Comment by Wondertan** [comment]
Agreed, yet sounds like it better be a metric

**Review by renaynay — COMMENTED** [review]
I agree with @Wondertan , this is better recorded as a metric.

**Comment by walldiss** [comment]
Metric would need logic implemented in this PR. There are 3 cases for hangups, so I would rather have specified log lines.  Also metrics are optional, but it will be important to be able to find those errors from logs in case this problem happens again

**Review by Wondertan — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]
Have we discussed making Put async?

**Comment by walldiss** [comment]
Async Put would just kick the can down the road.

**Pull request merged**
