### PR TITLE
refactoring(share/p2p): remove TTL in pubsub

### PR DESCRIPTION
**Pull request by vgonkivs**
## Overview
Return TTL back to the default value to avoid message duplication with the same msgID.

## Checklist
- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by renaynay** [comment]
Can you convert to draft @vgonkivs ? Let's test this first with testground. I'm not sure this resolves the issue.

**Comment by Wondertan** [comment]
This won't help. Because we never rebroadcast messages in the current code via PubSub means, as we always return ValidarionIgnore. We always rebroadcast manually Broadcast.


After thinking about this for a while, I think the actual problem is that we send notifications to everyone, including to those from who we already received the notification.

**Comment by vgonkivs** [comment]
Yeap, I agree that it will not help, but we don't need TTL=0 anyway

**Comment by Wondertan** [comment]
True, I agree that we can merge it as is. It does not fix the root problem, but it doesn't make it worse and removes a confusion configuration.

**Comment by renaynay** [comment]
@vgonkivs you can mark ready for review then, just change description

**Review by renaynay — APPROVED** [review]
okya just update the description

**Comment by Wondertan** [comment]
@vgonkivs, pls reference an issue this pr aimed to solve originally

**Pull request merged**
