### PR TITLE
Extend label automation to add external label

### PR DESCRIPTION
**Pull request by MSevey**
## Overview

Rene was interested in external issue labels, was easier to just do it then explain it in slack :-) 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Review by Wondertan — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Comment by Wondertan** [comment]
Seems like there is no `external` label created yet, will it automatically create one?

**Comment by Wondertan** [comment]
Can it mark PRs or only issues?

**Comment by MSevey** [comment]
> Seems like there is no `external` label created yet, will it automatically create one?

not sure, I went ahead and created a label just in case.

**Comment by MSevey** [comment]
> Can it mark PRs or only issues?

I'll follow up on the PRs, there is definitely a way to do it, just not sure if the current action will target PRs or if it is specific to issues.

**Comment by MSevey** [comment]
@Wondertan the `https://github.com/andymckay/labeler` action does support PR labels it looks like. 

If you'd like me to submit the change for that I'd recommend we merge this and then I would do a follow up as there are a few things I would need to test out.

**Comment by MSevey** [comment]
Also confirmed for the future that if the label doesn't exist it will be created when it is first run

**Pull request merged**
