### PR TITLE
nodebuilder: Remove current borked RPC tests in favour of implementing better ones with #962

### PR DESCRIPTION
**Pull request by renaynay**
New tests will replace these outdated ones in https://github.com/celestiaorg/celestia-node/issues/962.

The goal was to remove these tests from the start.

### CODE REVIEW

**Comment by Wondertan** [comment]
Two fails, hmm

**Comment by MSevey** [comment]
We want some sort of test like this in the future right? Does it make more sense just to `t.Skip("pending improvements")` so that we don't need to search for this PR to revert when we are ready?  We also then have the constant reminder in the CI about this test being skipped.

**Comment by renaynay** [comment]
Good point @MSevey . We need tests for our rpc but they definitely wouldn't and shouldn't be structured as the ones deleted in this PR. IMO, the new unit tests should be implemented along with the PR that impl this issue: https://github.com/celestiaorg/celestia-node/issues/962.

**Review by distractedm1nd — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]
👍🏻

**Pull request merged**
