### PR TITLE
Extract common parsing logic into single function.

### LINKED ISSUE #1331: cmd/celestia: Extract common parsing logic into single function
DRY the parsing logic inside the `PersistentPreRunE` fields for each node type (`bridge`, `light`, `full`).

### PR DESCRIPTION
**Pull request by HoytRen**
Closes #1331

When I compile cel-key, I see the binary is output to root, then I guess 'celestia' in the .igitigonre means the compiled binary, however it's moved to another place and not in root now.

### CODE REVIEW

**Comment by HoytRen** [comment]
The errors seem not on my side?

**Review by renaynay — CHANGES_REQUESTED** [review]
Thank you for this PR @HoytRen !

Two requests:

* please remove the `//nolint:dupl` directive at the top of `cmd/celestia/full.go` and `cmd/celestia/light.go`
* please remove the change made to the `.gitignore` file

**Comment by HoytRen** [comment]
Thanks for your guide. The lint problem is gone. I will leave the problem cause by .gitignore file by now, and let other people fix it later.

**Review by Wondertan — DISMISSED** [review]
Thanks and LGTM. Care for a .gitingore fix in the separate PR?

**Comment by HoytRen** [comment]
Sure, should I create another issue about the .gitignore first, or simply submit a PR? and I guess it's better to fix all detected problems once?

**Comment by Wondertan** [comment]
Yeah, let's also make an issue with the problem statement.

**Comment by HoytRen** [comment]
I can generate Bug Report and Feature Request only. Both of types seem not right. Should I generate bug report first and let you edit it later?

**Review by Wondertan — APPROVED** [review]

**Pull request merged**
