### PR TITLE
misc(header/headertest): Rename param for test suite to be more clear

### PR DESCRIPTION
**Pull request by renaynay**
I'm sorry but this was bothering me.

### CODE REVIEW

**Review by ramin — APPROVED** [review]

**Comment by Wondertan** [comment]
wut

**Comment by renaynay** [comment]
@Wondertan I always assumed the test suite would take `num` as number of headers to generate when really it was number of validators.

**Comment by Wondertan** [comment]
There is a comment that clearly states that this is validators, I don't think this is needed

**Comment by Wondertan** [comment]
Now part of #3139

**Pull request closed without merging**
