### PR TITLE
service/rpc: Return `/namespaced_data` and `/namespaced_shares` as flattened hex

### PR DESCRIPTION
**Pull request by renaynay**
Instead of returning some base64 encoded string, we should return `/namespaced_data` and `/namespaced_shares` as flattened, hex-encoded bytes.

### Request
```
curl -X GET <ip>:26658/namespaced_shares/ca0724d103a7c5bb/height/173350
```
### Response

```
{"shares":"ca0724d103a7c5bbc801d9a51f3b9c31a0af6ab37586e6cf50826e89e0dce53977b719e0ee221cbafde6b9eb02615485c94085d5e109938ba5b62c849e139e105690c4ab18ab824bb29fc872a0a245093a62db5a9f972d8a84d19866fc3ecd7192aaebe5218454fa7baa1e95896c44a0b3a09e6e033ee645dfa39c33f3bddcdb9fae07b26c37c6eed839b7d55c941c2c2aeb0e066596ec2c713f7f2e30453fa3445cee1e77fff91375b42a042dbba88d154bc851f5d214896d3418cc4d69a4cef50bcf707e9f9ab84e261675b22d9888973f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","height":173350}
```

### Request
```
curl -X GET <ip>:26658/namespaced_data/ca0724d103a7c5bb/height/173350
```
### Response

```
{"data":"d9a51f3b9c31a0af6ab37586e6cf50826e89e0dce53977b719e0ee221cbafde6b9eb02615485c94085d5e109938ba5b62c849e139e105690c4ab18ab824bb29fc872a0a245093a62db5a9f972d8a84d19866fc3ecd7192aaebe5218454fa7baa1e95896c44a0b3a09e6e033ee645dfa39c33f3bddcdb9fae07b26c37c6eed839b7d55c941c2c2aeb0e066596ec2c713f7f2e30453fa3445cee1e77fff91375b42a042dbba88d154bc851f5d214896d3418cc4d69a4cef50bcf707e9f9ab84e261675b22d9888973f","height":173350}
```

### CODE REVIEW

**Comment by vgonkivs** [comment]
Failed test will be fixed with https://github.com/celestiaorg/celestia-node/pull/1000

**Review by vgonkivs — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Review by adlerjohn — APPROVED** [review]
utACK

**Comment by Wondertan** [comment]
@distractedm1nd, pls rebase on main so we see that `TestFullReconstructFromBridge` is really fixed

**Comment by renaynay** [comment]
@Wondertan I'm not sure if @tzdybal wants this.

**Comment by tzdybal** [comment]
I just don't see any reason for this change. It doesn't fix any "burning" issue. I thought we're waiting for Public API to replace this.
For now, I'm afraid this will cause a lot of confusion and errors. Developers will have to know what version of node they query.
Plus, we have to change go-cnc and optimint accordingly, and the reason for compatibility break in un-versioned public API is only "cosmetics" IIUC.

But, OFC, I'll adopt the changes if this is merged :)

**Comment by renaynay** [comment]
Closing due to ^

**Pull request closed without merging**
