### PR TITLE
fix(share/p2p/peers): Prevent making pools for nil DataHash

### PR DESCRIPTION
**Pull request by renaynay**
Not critical, but if nil DataHash is broadcasted, node could create pool for empty datahash and just keep it around until garbage collected. Best to short-circuit instead and reject message.

### CODE REVIEW

**Comment by renaynay** [comment]
Actually this doesn't pass tests so converting to draft til i figure it out, will do tmw

**Comment by renaynay** [comment]
Actually we already do this inside of validate -

**Review by ramin — DISMISSED** [review]
seems reasonable, only suggestion might be to move the msg.DataHash.Validate() to be the first check so as to skip all the other checks proceeding first?

**Review by walldiss — APPROVED** [review]

**Review by ramin — APPROVED** [review]
:shipit:

**Review by distractedm1nd — APPROVED** [review]

**Pull request merged**
