### PR TITLE
changelog: release v0.1.1

### PR DESCRIPTION
**Pull request by Wondertan**

### CODE REVIEW

**Comment by liamsi** [comment]
There are merge conflicts. Is this a fix that is compatible to 0.1.0? Do we need to update any documentation in networks for this?

**Comment by Wondertan** [comment]
Yes
> Is this a fix that is compatible to 0.1.0?

Do we need to update any documentation in networks for this?
> No

**Review by liamsi — COMMENTED** [review]
It is not clear to me if this quickfix fixes the 0.1.0 release only. If there are breaking changes (which I would assume on master) then it's probably better to cut a 0.2.0 release?

**Comment by liamsi** [comment]
Why is there a release: https://github.com/celestiaorg/celestia-node/releases/tag/v0.1.1 before this got merged?

Can we have a somewhat consistent workflow with releases core here please?

**Comment by Wondertan** [comment]
No breaking changes here. Master is not included in 0.1.1, only a specific fix.

**Comment by Wondertan** [comment]
We don't have this for such a case. Where we are far away from the release in the master but need to incorporate a fix in past release and in master together.
> consistent workflow

**Comment by Wondertan** [comment]
I want to discuss the problem I've stumbled upon while doing this. The process is not that straightforward and CHANGELOG.md also creates problems.

**Comment by liamsi** [comment]
> No breaking changes here. Master is not included in 0.1.1, only a specific fix.

So this is a fix for 0.1.0, right? Then the flow could be:
create a `0.1.x` branch, create the fixes you want to include onto 0.1.x (which should have the same base as 0.1.0 first), open a PR, review, merge, release. Add thoe fixes to master as well.

**Comment by liamsi** [comment]
I also think we should clean up all these stale branches. 
There only should be 0.1.x (protected), master (protected) and a bunch of feature branches.

**Review by liamsi — APPROVED** [review]

**Review by renaynay — APPROVED** [review]

**Comment by renaynay** [comment]
> I also think we should clean up all these stale branches. There only should be v0.1.x (protected) and so on, master (protected) and a bunch of feature branches. For clarity: I mean `v0.1.x` as in https://github.com/tendermint/tendermint/tree/v0.35.x for instance. I do not mean we need a v0.1.1 branch.

This is why I like working off a fork :)

**Comment by Wondertan** [comment]
Also, I sent I did a git push --all and recovered all the deleted branched from local store. 🙈

**Review by adlerjohn — APPROVED** [review]

**Comment by liamsi** [comment]
And I was wondering where all these branches were coming from lol 🤣

**Comment by Wondertan** [comment]
deleting them

**Comment by Wondertan** [comment]
That was totally accidentally, done.
Need to build a habit to clean branches locally 😄

**Pull request merged**
