### PR TITLE
chore: add dupword CI && remove repetitive words globally

### PR DESCRIPTION
**Pull request by goofylfg**
use https://github.com/Abirdcfly/dupword to check duplicate words

output:
```
celestia-node/share/eds/retriever_quadrant.go:71:4: Duplicate words (into) found
celestia-node/share/availability/full/reconstruction_test.go:179:2: Duplicate words (L) found
celestia-node/share/getters/getter_test.go:338:2: Duplicate words (D) found
celestia-node/share/p2p/peers/manager_test.go:86:3: Duplicate words (be) found
```

### CODE REVIEW

**Comment by ramin** [comment]
hi @goofylfg thank you! I thought i had caught all these 😄 

Generally, we tend NOT to accept simple grammar/spelling fixes. That said, this project uses `golangci-lint` and has a CI integration to run it. It also appears `dupword` can be enabled https://golangci-lint.run/usage/linters/#dupword. 

It appears it would be fairly trivial to enable dupword in our config, and modify this PR so the contribution is enabling dupword in our linter, then have the fixes accompany that as a change. This is something we'd appreciate and accept. 

Would you be interested in giving it a go?

**Comment by goofylfg** [comment]
> hi @goofylfg thank you! I thought i had caught all these 😄
> 
> Generally, we tend NOT to accept simple grammar/spelling fixes. That said, this project uses `golangci-lint` and has a CI integration to run it. It also appears `dupword` can be enabled https://golangci-lint.run/usage/linters/#dupword.
> 
> It appears it would be fairly trivial to enable dupword in our config, and modify this PR so the contribution is enabling dupword in our linter, then have the fixes accompany that as a change. This is something we'd appreciate and accept.
> 
> Would you be interested in giving it a go?

sure, I will add dupword CI integration.

**Comment by goofylfg** [comment]
```
celestia-node/share/eds/retriever_quadrant.go:71:4: Duplicate words (into) found
celestia-node/share/availability/full/reconstruction_test.go:179:2: Duplicate words (L) found
celestia-node/share/getters/getter_test.go:338:2: Duplicate words (D) found
celestia-node/share/p2p/peers/manager_test.go:86:3: Duplicate words (be) found
```
"L","D" is false positve, so I added it to ignore list. @ramin  plz check it ~

**Comment by ramin** [comment]
@goofylfg oh awesome nice job! My only request would be to do `//nolint:dupword` for those `_test.go` files (either whole file, or the area with the false positive) vs adding to config for single letters like that, then IMO it's gtg

**Comment by goofylfg** [comment]
> @goofylfg oh awesome nice job! My only request would be to do `//nolint:dupword` for those `_test.go` files (either whole file, or the area with the false positive) vs adding to config for single letters like that, then IMO it's gtg

fixed, thks for the feedback @ramin

**Review by ramin — APPROVED** [review]
nice work @goofylfg

**Review by vgonkivs — APPROVED** [review]

**Pull request merged**
