### PR TITLE
chore: bump go-libp2p-pubsub

### PR DESCRIPTION
**Pull request by Wondertan**
A regular bump

### CODE REVIEW

**Comment by Wondertan** [comment]
There is unit test failing. Need some time to debug

```
     --- FAIL: TestPubSub/valid_height,_valid_hash (0.30s)
        pubsub_test.go:118: 
            	Error Trace:	/home/runner/work/celestia-node/celestia-node/share/p2p/shrexsub/pubsub_test.go:118
            	Error:      	Received unexpected error:
            	            	context deadline exceeded
            	Test:       	TestPubSub/valid_height,_valid_hash
```

**Comment by ramin** [comment]
@Wondertan re-running, might be a flake

**Comment by Wondertan** [comment]
I tried re-running once and that didn't help

**Review by ramin — APPROVED** [review]

**Comment by ramin** [comment]
@Wondertan it worked!!! YAY

**Review by walldiss — APPROVED** [review]

**Pull request merged**
