### PR TITLE
Fix start with chain id mismatch

### PR DESCRIPTION
**Pull request by jpserrat**
Now returning an error if there is a chain ID mismatch. I had to add the network to the core accessor build params, I tried to get the network using the `cmd.Network(ctx)` but unfortunately it is not possible due to cycle imports.

One question unrelated to the issue: I noticed that `client.WaitForStateChange(ctx, connectivity.Ready)` is being used to check if the grpc client is connected, shouldn't this be `client.WaitForStateChange(ctx, connectivity.Idle)`?

Closes: #3597

cc: @renaynay @jcstein

### CODE REVIEW

**Comment by Wondertan** [comment]
>  shouldn't this be client.WaitForStateChange(ctx, connectivity.Idle)

Why Idle over Ready?

**Comment by jpserrat** [comment]
The doc says `WaitForStateChange waits until the connectivity.State of ClientConn changes from sourceState`. In this case, the source state is `Ready` and `WaitForStateChange` will return true cause the initial state is `Idle`. The source state should be `Idle` to ensure a status change.

**Review by renaynay — COMMENTED** [review]
can confirm this works: 

```
Error: node: failed to start: wrong network provided in core.ip url for chain id: celestia
```

One thing I would ask for is a better err msg (wrong network in core.ip endpoint, expected %s, got %s)

**Review by renaynay — COMMENTED** [review]
also please lint @jpserrat  🙏🏻

**Comment by jcstein** [comment]
works for me at latest commit `Error: node: failed to start: wrong network in core.ip endpoint, expected celestia, got mocha-4`:

```log
celestia light start --core.ip rpc.celestia.pops.one --p2p.network mocha
2024-09-16T12:21:44.819+0200	INFO	node	nodebuilder/module.go:27	Accessing keyring...
2024-09-16T12:21:45.132+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/levels.go:171	All 461 tables opened in 269ms

2024-09-16T12:21:45.141+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/discard.go:66	Discard stats nextEmptySlot: 83

2024-09-16T12:21:45.141+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:368	Set nextTxnTs to 21718473
2024-09-16T12:21:46.080+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/levels.go:1498	This Range (numTables: 1)
Left:
00000000  2f 68 65 61 64 65 72 73  2f 31 37 46 41 39 43 34  |/headers/17FA9C4|
00000010  34 32 31 39 34 39 46 42  42 39 36 46 41 37 36 33  |421949FBB96FA763|
00000020  41 44 45 31 34 38 45 43  45 37 32 42 45 39 37 37  |ADE148ECE72BE977|
00000030  37 30 45 38 45 42 32 33  38 39 33 34 39 33 39 32  |70E8EB2389349392|
00000040  32 46 38 31 44 34 39 42  33 00 00 00 00 00 00 00  |2F81D49B3.......|
00000050  00                                                |.|

Right:
00000000  2f 68 65 61 64 65 72 73  2f 45 41 38 36 35 36 38  |/headers/EA86568|
00000010  45 44 33 36 39 43 33 42  41 42 37 33 39 36 38 32  |ED369C3BAB739682|
00000020  37 38 30 42 35 33 36 41  41 31 32 44 30 42 39 31  |780B536AA12D0B91|
00000030  46 37 43 36 31 37 41 41  35 45 33 34 41 35 37 37  |F7C617AA5E34A577|
00000040  42 43 45 39 43 38 39 41  37 ff ff ff ff ff ff ff  |BCE9C89A7.......|
00000050  ff                                                |.|


2024-09-16T12:21:46.080+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/levels.go:1500	Next Range (numTables: 23)
Left:
00000000  2f 68 65 61 64 65 72 73  2f 31 37 34 31 39 30 37  |/headers/1741907|
00000010  00 00 00 00 00 00 00 00                           |........|

Right:
00000000  2f 68 65 61 64 65 72 73  2f 45 44 43 30 41 35 31  |/headers/EDC0A51|
00000010  34 38 32 41 38 30 45 42  31 39 38 31 33 31 34 31  |482A80EB19813141|
00000020  45 39 32 37 39 37 35 30  36 45 43 37 45 46 32 30  |E92797506EC7EF20|
00000030  38 45 43 45 32 44 41 46  35 33 31 35 31 33 43 46  |8ECE2DAF531513CF|
00000040  37 35 46 46 43 37 45 37  30 ff ff ff ff ff ff ff  |75FFC7E70.......|
00000050  ff                                                |.|


2024-09-16T12:21:46.470+0200	INFO	module/p2p	p2p/tls.go:54using a default ws transport
2024-09-16T12:21:46.495+0200	INFO	pidstore	pidstore/pidstore.go:67	Loaded peers from disk	{"amount": 93}
2024-09-16T12:21:46.495+0200	INFO	module/header	header/config.go:66	No trusted peers in config, initializing with default bootstrappers as trusted peers
2024-09-16T12:21:46.500+0200	INFO	header/p2p	p2p/exchange.go:99	client: starting client	{"protocol ID": "/mocha-4/header-ex/v0.0.3"}
2024-09-16T12:21:46.500+0200	INFO	pidstore	pidstore/pidstore.go:67	Loaded peers from disk	{"amount": 93}
2024-09-16T12:21:46.500+0200	INFO	header/store	store/store.go:193	loaded head	{"height": 2607724, "hash": "55FC970E55AA9DA78E112EE65993081CCDCE2D09CD52C63F8718F083A3E4A2A8"}
2024-09-16T12:21:46.500+0200	INFO	header/p2p	p2p/subscriber.go:80	joining topic	{"topic ID": "/mocha-4/header-sub/v0.0.1"}
2024-09-16T12:21:46.500+0200	INFO	fraudserv	fraudserv/helpers.go:29	joining topic	{"id": "/mocha-4/fraud-sub/badencodingv0.1/v0.0.1"}
2024-09-16T12:21:46.500+0200	INFO	fraudserv	fraudserv/service.go:114	starting fraud proof service	{"protocol ID": "/mocha-4/fraud/v0.0.1"}
2024-09-16T12:21:46.821+0200	WARN	header/p2p	p2p/subscriber.go:91	unregistering validator: no validator for topic /mocha-4/header-sub/v0.0.1
2024-09-16T12:21:46.821+0200	INFO	pidstore	pidstore/pidstore.go:84	Persisted peers successfully	{"amount": 2}
2024-09-16T12:21:46.822+0200	ERROR	fraudserv	fraudserv/sync.go:74	error while requesting fraud proofs	{"err": "stream reset", "peer": "12D3KooWK6wJkScGQniymdWtBwBuU36n6BRXp9rCDDUD6P5gJr3G"}
2024-09-16T12:21:46.822+0200	ERROR	fraudserv	fraudserv/sync.go:74	error while requesting fraud proofs	{"err": "stream reset", "peer": "12D3KooWCBAbQbJSpCpCGKzqz3rAN4ixYbc63K68zJg9aisuAajg"}
2024-09-16T12:21:46.822+0200	INFO	basichost	basic/natmgr.go:112	DiscoverNAT error:no NAT found
2024-09-16T12:21:46.822+0200	WARN	blockstore	blockstore/bloom_cache.go:41	Cache rebuild closed by context finishing: context canceled
2024-09-16T12:21:46.823+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:546	Lifetime L0 stalled for: 0s

2024-09-16T12:21:46.853+0200	INFO	badger4	v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:625	
Level 0 [ ]: NumTables: 00. Size: 0 B of 0 B. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 16 MiB
Level 1 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 2 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 3 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 4 [ ]: NumTables: 00. Size: 0 B of 46 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 4.0 MiB
Level 5 [B]: NumTables: 66. Size: 451 MiB of 459 MiB. Score: 0.00->0.00 StaleData: 85 KiB Target FileSize: 8.0 MiB
Level 6 [ ]: NumTables: 394. Size: 4.5 GiB of 4.5 GiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 16 MiB
Level Done

Error: node: failed to start: wrong network in core.ip endpoint, expected celestia, got mocha-4
```

**Review by renaynay — APPROVED** [review]
👍🏻

**Review by cristaloleg — DISMISSED** [review]
SGTM

**Review by cristaloleg — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]

**Pull request merged**
