### PR TITLE
chore: rename Repository to Store

### LINKED ISSUE #146: node: rename Repository to Store.
## Problem
There were multiple confusions about the naming of the `Repository` interface, so to make everyone happy and to avoid further confusions we need to rename Repository to a more common Store name. The functionality and purpose should stay the same. 

## Actions
* Rename Repository to Store in code
* Ensure all the var/flag/doc names are consistent with the renaming.

### PR DESCRIPTION
**Pull request by Wondertan**
Just renamings. Closes #146, #126

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
noice. 

Im guessing in the future store_memdb will be moved into its own store package?

**Comment by Wondertan** [comment]
`store_memdb` ?

**Review by Bidon15 — APPROVED** [review]
Approvoor replicator instantiated

**Review by renaynay — APPROVED** [review]
Lgtm

**Pull request merged**
