### PR TITLE
fix!(blob/module): fix api by changing variadic params to a slice

### PR DESCRIPTION
**Pull request by vgonkivs**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by distractedm1nd — DISMISSED** [review]
next step is adding tests for our most critical rpc methods

**Review by walldiss — DISMISSED** [review]

**Review by Wondertan — APPROVED** [review]

**Review by renaynay — APPROVED** [review]

**Comment by Wondertan** [comment]
Let's double check we removed all the variadics in ___all modules___

**Review by renaynay — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]
Looks great. Another great test to add would be the full blob module lifecycle over RPC (trying to use all the methods)

**Comment by vgonkivs** [comment]
closing in favour of #2298

**Pull request closed without merging**
