### PR TITLE
deps: bump rsmt2d to 0.5.0

### PR DESCRIPTION
**Pull request by Wondertan**
I tried updating to this version before but didn't like that we needed to keep both flattened and imported squares, so that code became even bulkier for the next currently unpushed iteration of Retriever, so I decided to wait until the requested rsmt2d API changes to land before upgrading(cc @adlerjohn), but now we have to update as core updated already.

### CODE REVIEW

**Comment by Wondertan** [comment]
image
🤔

**Comment by Wondertan** [comment]
@adlerjohn, I just rerun it, and now it works. I didn't change anything; it seems like some bug on CI. This happened specifically during the build of the integration testis jobs

**Review by renaynay — APPROVED** [review]
utACK but soon the requested changes to rsmt2d api will be pushed and we'll refactor again -- refactor to maintain `squareImported` or the flattened shares? @Wondertan

**Comment by Wondertan** [comment]
@renaynay, refactor to remove flattened shares + remove codec and tree constructor from session and setting shares directly into the imported square. Maybe a few more things

**Review by Bidon15 — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Pull request merged**
