### PR TITLE
feat(rpc): add daser cmd

### PR DESCRIPTION
**Pull request by vgonkivs**
## Overview
Added `sampling-stats` cmd that allows to get current das status 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by Wondertan** [comment]
Laser cmd😆

**Comment by distractedm1nd** [comment]
i want a laser command so bad

**Comment by vgonkivs** [comment]
Usage: `celestia destroy [peer.ID]`

**Review by distractedm1nd — APPROVED** [review]

**Review by ramin — APPROVED** [review]
:shipit:

**Pull request merged**
