### PR TITLE
fix(nodebuilder/das): Skip config validation for bridge node

### PR DESCRIPTION
**Pull request by renaynay**
Related to #1372

### CODE REVIEW

**Review by distractedm1nd — APPROVED** [review]

**Comment by Wondertan** [comment]
Hmm, it does not seem to fix the issue attached

**Comment by renaynay** [comment]
@Wondertan yes it will still emit the DASer config but it won't validate it since it does not need it.

**Comment by Wondertan** [comment]
It does not fix the attached issue, that's the point.

**Comment by distractedm1nd** [comment]
I updated the burntsushi toml dep which now has a working omitempty, so an empty daser config is now not included in the TOML file. I also refactored the readwrite config test to run all node types.

**Review by Wondertan — APPROVED** [review]
Did you do a sanity check by initializing a new Bridge node?

**Comment by distractedm1nd** [comment]
@Wondertan yes, it works - that part of the config is not included in the toml then. And it has no problems using it on start

**Review by distractedm1nd — APPROVED** [review]
Excellent hack w/ the toml tag, great work

**Pull request merged**
