### PR TITLE
refactoring!(libs/header): simplify return params in store.Append

### PR DESCRIPTION
**Pull request by vgonkivs**
## Overview
Amount of added headers to the store is redundant information, IMO. The only thing that we should know is whether `Append` was successful or not
## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
Originally, when verification of headers happend only on Store level, it made sense to have such protection, as networking layer could give us incorrect header somewhere in between the range. Now, as we moving towards VerifiedRangeByHeight this becomes unnecessary and we can safely remove it.

**Comment by Wondertan** [comment]
Also not that this is breaking and refactor type of PR, not misc

**Review by Wondertan — APPROVED** [review]

**Comment by Wondertan** [comment]
Units are still seems to be failing on CI

**Review by Wondertan — APPROVED** [review]
Not a feature but refactoring

**Comment by Wondertan** [comment]
@vgonkivs, why dic you remove breaking?

**Review by renaynay — APPROVED** [review]

**Comment by renaynay** [comment]
PR is breaking, pls mark

**Pull request merged**
