### PR TITLE
docker: Update entrypoint.sh for multiple networks

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

This commit adds a `--p2p.network` flag to the start command in `entrypoint.sh`. This resolves https://github.com/celestiaorg/celestia-node/issues/1502 and https://github.com/celestiaorg/celestia-node/issues/1508

## Checklist

- [ ] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Review by distractedm1nd — DISMISSED** [review]

**Review by Wondertan — DISMISSED** [review]
utACK

**Review by renaynay — COMMENTED** [review]
we should also set `P2P_NETWORK` env in Dockerfile itself otherwise this will fail if not provide a default (default should be mocha)

**Review by renaynay — CHANGES_REQUESTED** [review]
we should also set P2P_NETWORK env in Dockerfile itself otherwise this will fail if not provide a default (default should be mocha)

**Comment by jcstein** [comment]
thank you @renaynay - I'll be getting to that this week and will try that out too

**Comment by jcstein** [comment]
what's the proper way to test this out? when working off of this PR, I can't seem to get image to build from this file

```sh
docker build docker/

[+] Building 0.5s (10/14)
 => [internal] load build definition from Dockerfile                  0.0s
 => => transferring dockerfile: 37B                                   0.0s
 => [internal] load .dockerignore                                     0.0s
 => => transferring context: 2B                                       0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04       0.4s
 => [internal] load metadata for docker.io/library/golang:1.19        0.4s
 => CANCELED [builder 1/6] FROM docker.io/library/golang:1.19@sha256  0.0s
 => => resolve docker.io/library/golang:1.19@sha256:660f138b4477001d  0.0s
 => => sha256:660f138b4477001d65324a51fa158c1b868651 2.36kB / 2.36kB  0.0s
 => CACHED [stage-1 1/3] FROM docker.io/library/ubuntu:20.04@sha256:  0.0s
 => [internal] load build context                                     0.0s
 => => transferring context: 65B                                      0.0s
 => ERROR [stage-1 2/3] COPY docker/entrypoint.sh /                   0.0s
 => CACHED [builder 2/6] WORKDIR /src                                 0.0s
 => ERROR [builder 3/6] COPY go.mod go.sum ./                         0.0s
------
 > [stage-1 2/3] COPY docker/entrypoint.sh /:
------
------
 > [builder 3/6] COPY go.mod go.sum ./:
------
failed to compute cache key: "/docker/entrypoint.sh" not found: not found
```

when running in `/docker` directory

```sh
docker build .

[+] Building 0.2s (10/14)
 => [internal] load build definition from Dockerfile                                        0.0s
 => => transferring dockerfile: 37B                                                         0.0s
 => [internal] load .dockerignore                                                           0.0s
 => => transferring context: 2B                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                             0.2s
 => [internal] load metadata for docker.io/library/golang:1.19                              0.1s
 => CACHED [stage-1 1/3] FROM docker.io/library/ubuntu:20.04@sha256:0e0402cd13f68137edb026  0.0s
 => CANCELED [builder 1/6] FROM docker.io/library/golang:1.19@sha256:660f138b4477001d65324  0.0s
 => => resolve docker.io/library/golang:1.19@sha256:660f138b4477001d65324a51fa158c1b868651  0.0s
 => => sha256:660f138b4477001d65324a51fa158c1b868651b44e43f0953bf062e9f38b 2.36kB / 2.36kB  0.0s
 => [internal] load build context                                                           0.0s
 => => transferring context: 65B                                                            0.0s
 => ERROR [stage-1 2/3] COPY docker/entrypoint.sh /                                         0.0s
 => CACHED [builder 2/6] WORKDIR /src                                                       0.0s
 => ERROR [builder 3/6] COPY go.mod go.sum ./                                               0.0s
------
 > [stage-1 2/3] COPY docker/entrypoint.sh /:
------
------
 > [builder 3/6] COPY go.mod go.sum ./:
------
failed to compute cache key: "/docker/entrypoint.sh" not found: not found
```

**Comment by jcstein** [comment]
running from `celestia-node` directory: `docker build . -t celestia-node -f docker/Dockerfile`

**Comment by jcstein** [comment]
afaik, the image works correctly, although arabica is down

`docker run -e NODE_TYPE=light -e P2P_NETWORK=arabica celestia-node celestia light start --core.ip https://limani.celestia-devops.dev --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network arabica`

log for build: https://app.warp.dev/block/WjhAiA5z9ONE7vUwnuCW1u

log for run (errors as expected): https://app.warp.dev/block/7tObINfBU6WX2wXRDKYYSa

**Review by Wondertan — APPROVED** [review]
Thanks you

**Comment by jcstein** [comment]
you're welcome. let me know if there's other testing to do!

**Comment by jcstein** [comment]
updated docs ahead of `v0.6.2` release: https://github.com/celestiaorg/docs/pull/381/commits/f080832b2c61f28650680deba1575699b3731136

**Review by renaynay — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Pull request merged**
