### PR TITLE
ipld: fix shares ordering

### LINKED ISSUE #621: `GetSharesByNamespace` returns shares in non-deteministic order
[`GetSharessByNamespace`](https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L153) spawns a goroutine for each `roodCID`, and results are returned via channel, and appended to an array:
https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L188

Because of this, the order of returned shares is non-deterministic.

### PR DESCRIPTION
**Pull request by vgonkivs**
Resolves #621 .
Tested on [pr](https://github.com/celestiaorg/celestia-node/pull/626/files#diff-1be0e957da57e59d655a4543e06fe2966028e5329acde5d85377e99ddac2e361R144)

### CODE REVIEW

**Review by adlerjohn — APPROVED** [review]

**Review by renaynay — APPROVED** [review]
Wow what a fix 😂

**Comment by Wondertan** [comment]
Can you pls update tests to include ordering check

**Comment by adlerjohn** [comment]
We should use the go-critic linter: https://github.com/go-critic/go-critic/pull/1034

**Comment by vgonkivs** [comment]
Closing in favour of #626

**Pull request closed without merging**
