### PR TITLE
params: Fix issue in `CELESTIA_CUSTOM` to be able to parse genesis even if bootstrappers not provided

### LINKED ISSUE #776: Genesis Hash in CELESTIA_CUSTOM is parsed only when bootstrappers are not provided
It's not possible to use custom genesis hash and bootstrappers at the same time.

The condition checks for exact value: https://github.com/celestiaorg/celestia-node/blob/f22aae25867c0734ad29da61218d63f477f99683/params/default.go#L38

This should be changed to `>= 2`.

### PR DESCRIPTION
**Pull request by renaynay**
Resolves #776

### CODE REVIEW

**Review by Wondertan — APPROVED** [review]
😄

**Comment by Wondertan** [comment]
wtf?
image

**Review by tzdybal — APPROVED** [review]
:)

**Review by adlerjohn — APPROVED** [review]
utACK

**Pull request merged**
