### PR TITLE
fix: remove root from traces

### PR DESCRIPTION
**Pull request by vgonkivs**
## Overview
Self-explanatory

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
The fact that we remove roots makes most of the traces meaningless(besides the time which can be done by metrics anyway). Maybe there is a way to disable searching by this attribute to keep roots while solving cardinality? 
cc @walldiss

**Comment by Wondertan** [comment]
Good idea @renaynay. Saving root only on error would remove my concern.

**Comment by walldiss** [comment]
Traces will still contain all info from trace parent, that is stored in context. 
The problem is that root hashes is a bottleneck for tracing collection performance. The fact that 5 instances jaeger instances can serve traces from only 2 nodes is quite bad. 
Those attributes were added because they looked free, but they are not. As for now since we don't know for sure the use cases for those attributes it is fine remove them altogether and add once we absolutely need to.

**Comment by renaynay** [comment]
Okay so @vgonkivs is there a way to just track root as attribute specifically if an error is recorded?

**Comment by Wondertan** [comment]
We understand the problem. 
The concern is why do we need traces at all here if in most cases it does not bring any additional info besides just execution time that is better be covered by metrics? @renaynay‘s idea to include such additional info brings value on demand during the error. 

I don't wanna block this PR and we can move this discussion to the issue, as I want to know why not to remove the traces from here altogether or make them useful.

**Comment by vgonkivs** [comment]
> Okay so @vgonkivs is there a way to just track root as attribute specifically if a critical error is recorded?

Yes, we can leave `root` only for error cases. @walldiss wdyt?

**Review by renaynay — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]

**Pull request merged**
