### PR TITLE
ci(deps): Bump common ci

### PR DESCRIPTION
**Pull request by jrmanes**
hello team!

this PR bumps the version to the latest common [0.3.2](https://github.com/celestiaorg/.github/releases/tag/v0.3.2)

cheers! 🚀

### CODE REVIEW

**Review by Wondertan — APPROVED** [review]

**Review by walldiss — APPROVED** [review]

**Comment by MSevey** [comment]
merge is pending branch protection rule updates for the new CI name detailed in the release notes.

**Review by MSevey — APPROVED** [review]

**Comment by Wondertan** [comment]
It's still waiting for it

**Comment by Wondertan** [comment]
There is something wrong with CI on this PR. It does not let merge to go through

**Comment by ramin** [comment]
@Wondertan it changes task names so invalidates some checks, needs an admin to reconfigure required checks to pass

**Pull request merged**
