### PR TITLE
fix(share/eds)!: use separate badger for inverted index

### PR DESCRIPTION
**Pull request by walldiss**
Having same badger instance for dagstore shards and inverted index has proven to have hangup on `Put` operation for 1-10min. During tests it has shown, that splitting badger into 2 instances solves the hangup issue. 

Also once https://github.com/celestiaorg/celestia-node/issues/2479 is implemented and inverted index will needs to be removed. Separate badger will be much easier for users migration.

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
> Having same badger instance for dagstore shards and inverted index has proven to have hangup on Put operation for 1-10min. 

According to @musalbas, no hangup happens with a single instance with 20 compactors. Is it worth verifying again to avoid having two badgers when we can have one only?

**Comment by walldiss** [comment]
Considering inverted index is major bottleneck right now an we plan to remove it soon. I think it is worth to do separate badgers just for sake of easy migration.

If we keep inverted index in same badger as shards badger, we would need to manually remove each key. It would mean to find all keys by prefix and remove them one by one, which will take ages.

I've started test to try 20 compactors on single badger

**Comment by Wondertan** [comment]
Agreed

**Review by Wondertan — DISMISSED** [review]

**Comment by Wondertan** [comment]
We still may wanna keep all the storage breaking PRs together

**Review by distractedm1nd — APPROVED** [review]

**Review by Wondertan — APPROVED** [review]

**Review by distractedm1nd — APPROVED** [review]

**Pull request merged**
