### PR TITLE
fix(ipld/plugin): don't truncate a type byte when it's not in the data

### PR DESCRIPTION
**Pull request by Wondertan**
The code has a special case for the share data with type byte and without. However, it truncates the type byte like it is always there.
The #1139 is the first user of share data without a type byte, which uncovered the bug. The type byte causes issues for us again.

#### refactor(ipld/plugin): extract namespaceHasher into a separate file with some additional cleanups

In preparation for the upcoming test for the namespaceHasher, we extract it into a separate file. Also, some additional cosmetics were done
reducing the API surfuce of the pkg, hiding things that are not supposed to be used outside.

#### perf(ipld/plugin): use sha256-simd to gain 40% speedup for hash computations

### CODE REVIEW

**Comment by renaynay** [comment]
nice find

**Review by renaynay — DISMISSED** [review]

**Comment by renaynay** [comment]
Should we have a test for this as well? we don't have coverage for Write in the current tests.

**Review by distractedm1nd — CHANGES_REQUESTED** [review]
I agree that we should add some test coverage - not only for having tests, but also as a sort of "secondary documentation" showing usage

**Comment by Wondertan** [comment]
I'll add a simple test. Re "secondary documentation": this hasher is not supposed to be used outside.

**Review by distractedm1nd — APPROVED** [review]

**Review by vgonkivs — APPROVED** [review]

**Pull request merged**
